[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "flash loan rough gloom inherit destroy often rescue shoe slogan wisdom enhance figure capital pattern scare then okay theory economy next hurry illegal off"
